twist_mux:
  ros__parameters:
    use_stamped_vel: false    # ← zmień na false
    output: /diff_cont/cmd_vel          # ← zmień z /cmd_vel_mux
    topics:
      navigation:
        topic: /cmd_vel_nav   # ← zmień żeby nie było pętli
        timeout: 0.5
        priority: 10
      joystick:
        topic: cmd_vel_joy
        timeout: 0.5
        priority: 100